In [4]:
import numpy as np

In [5]:
#empty array 
arr1=np.array([])
arr1

array([], dtype=float64)

In [6]:
type(arr1)

numpy.ndarray

In [7]:
t1=(23,4,7.6,1,3)
type(t1)

tuple

In [11]:
arr2=np.array(t1)
arr2

array([23. ,  4. ,  7.6,  1. ,  3. ])

In [12]:
type(arr2)

numpy.ndarray

In [14]:
arr2.dtype #data type of elements of array

dtype('float64')

In [31]:
len(arr2) #length of array

5

In [32]:
arr2.ndim # no of dimensions 

1

In [34]:
arr2.size #size of the elements

5

In [35]:
arr2.shape #return no of rows and columns 

(5,)

### 2d array

In [15]:
nested_list=[[1,5],[2,6],[5,7]]

In [16]:
arr3=np.array(nested_list)

In [17]:
arr3.ndim

2

In [18]:
arr3.shape

(3, 2)

In [19]:
arr3.size

6

# 3d array

In [20]:
nested_list2=[[
    [2,4,5],[3,6,1],[7,14,25],[13,26,11]
]
             ]

In [21]:
arr4=np.array(nested_list2)

In [22]:
arr4.ndim

3

In [23]:
arr4.shape

(1, 4, 3)

In [24]:
arr4.size

12

In [26]:
nested_list2=[ [
              [2,4,5],[3,6,1],
             ],
              [
               [7,14,25],[13,26,11]
              ]

             ]

In [27]:
arr4=np.array(nested_list2)

In [28]:
arr4.shape

(2, 2, 3)

In [29]:
    arr4.size

12

In [30]:
arr4.ndim

3

## Built in Function to generate
## arrangwe

In [38]:
a1=np.arange(10) #0 till 10-1
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
a2=np.arange(5,24)# 5 till 24
a2

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23])

In [43]:
a3=np.arange(2,22,3 )# 2till 22 with a step of 3
a3

array([ 2,  5,  8, 11, 14, 17, 20])

In [44]:
a3=np.arange(20,2,-2)# 2till 22 with a step of 3
a3

array([20, 18, 16, 14, 12, 10,  8,  6,  4])

## Linspace --->generates array elements of decimal values within a given range

In [46]:
a4=np.linspace(10,80) #generates 50 elments by default
a4

array([10.        , 11.42857143, 12.85714286, 14.28571429, 15.71428571,
       17.14285714, 18.57142857, 20.        , 21.42857143, 22.85714286,
       24.28571429, 25.71428571, 27.14285714, 28.57142857, 30.        ,
       31.42857143, 32.85714286, 34.28571429, 35.71428571, 37.14285714,
       38.57142857, 40.        , 41.42857143, 42.85714286, 44.28571429,
       45.71428571, 47.14285714, 48.57142857, 50.        , 51.42857143,
       52.85714286, 54.28571429, 55.71428571, 57.14285714, 58.57142857,
       60.        , 61.42857143, 62.85714286, 64.28571429, 65.71428571,
       67.14285714, 68.57142857, 70.        , 71.42857143, 72.85714286,
       74.28571429, 75.71428571, 77.14285714, 78.57142857, 80.        ])

In [47]:
a4.size

50

In [49]:
a5=np.linspace(1,10,30)
a5

array([ 1.        ,  1.31034483,  1.62068966,  1.93103448,  2.24137931,
        2.55172414,  2.86206897,  3.17241379,  3.48275862,  3.79310345,
        4.10344828,  4.4137931 ,  4.72413793,  5.03448276,  5.34482759,
        5.65517241,  5.96551724,  6.27586207,  6.5862069 ,  6.89655172,
        7.20689655,  7.51724138,  7.82758621,  8.13793103,  8.44827586,
        8.75862069,  9.06896552,  9.37931034,  9.68965517, 10.        ])

In [50]:
a5.size

30

# retstep=True --returns the interval

In [52]:
a5=np.linspace(23,100,20,retstep=True)
a5

(array([ 23.        ,  27.05263158,  31.10526316,  35.15789474,
         39.21052632,  43.26315789,  47.31578947,  51.36842105,
         55.42105263,  59.47368421,  63.52631579,  67.57894737,
         71.63157895,  75.68421053,  79.73684211,  83.78947368,
         87.84210526,  91.89473684,  95.94736842, 100.        ]),
 4.052631578947368)

In [53]:
a5[0].size

20

# reshape()-- changes the shape of the array

In [54]:
arr3

array([[1, 5],
       [2, 6],
       [5, 7]])

In [55]:
arr3.shape

(3, 2)

In [ ]:
#Note: while reshaping put the shape of multiple of total size of elements only

In [58]:
arr3_reshape=arr3.reshape((2,3))# change the shape of arr3 from (3,2) to (2,3)
arr3_reshape

array([[1, 5, 2],
       [6, 5, 7]])

In [59]:
arr2

array([23. ,  4. ,  7.6,  1. ,  3. ])

In [60]:
arr4

array([[[ 2,  4,  5],
        [ 3,  6,  1]],

       [[ 7, 14, 25],
        [13, 26, 11]]])

In [61]:
arr4.shape

(2, 2, 3)

In [63]:
arr4.reshape((1,4,3))

array([[[ 2,  4,  5],
        [ 3,  6,  1],
        [ 7, 14, 25],
        [13, 26, 11]]])

In [64]:
arr4.reshape((12,))

array([ 2,  4,  5,  3,  6,  1,  7, 14, 25, 13, 26, 11])

In [65]:
arr1_list=[[2,4],
           [3,4],
           [6,2],
           [5,3]
          ]
           

In [67]:
arr1=np.array(arr1_list)
arr1

array([[2, 4],
       [3, 4],
       [6, 2],
       [5, 3]])

In [68]:
arr1.reshape((2,4))

array([[2, 4, 3, 4],
       [6, 2, 5, 3]])

# Zeros() and ones()

In [69]:
a6=np.zeros(3,dtype=int)
a6

array([0, 0, 0])

In [70]:
a7=np.zeros((3,4),dtype=int)
a7

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [71]:
a6=np.ones(3,dtype=int)
a6

array([1, 1, 1])

In [72]:
a6=np.ones(5,dtype=int)
a6

array([1, 1, 1, 1, 1])

In [75]:
a9=np.ones((2,2,5))#1st one is for two times 2d array and 2nd element is for 2 rows and 2 columns 
a9

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [76]:
a9.ndim

3

## eye()-- it generates identity matrix

In [79]:
a10=np.eye(5,5)# here all diagonal elemnts will be same 
a10

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [81]:
a11=np.eye(3))# here all diagonal elemnts will be same 
a11

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Broadcasting in an array

In [ ]:
Broadcasting means ability to acess every elemnt of the array and perform operations on it

In [82]:
a11 #3-1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [84]:
ans=a11 * 3-1
ans

array([[ 2., -1., -1.],
       [-1.,  2., -1.],
       [-1., -1.,  2.]])

In [85]:
ans/ans

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [86]:
ans**2

array([[4., 1., 1.],
       [1., 4., 1.],
       [1., 1., 4.]])

# Array generation using random elements

# rand()-- generates random numbers from 0 to 1 range

In [87]:
np.random.rand()#1sr\t

0.8126324103893342

In [90]:
a12=np.random.rand(10) #generates 10 elements within  0 to 1 range #2nd way
a12

array([0.30946072, 0.86109714, 0.41775177, 0.07454422, 0.17793225,
       0.3608587 , 0.73826993, 0.48588124, 0.90816457, 0.02760697])

In [92]:
a13=a12.reshape(5,2)#reshape generated array to 2D
a13

array([[0.30946072, 0.86109714],
       [0.41775177, 0.07454422],
       [0.17793225, 0.3608587 ],
       [0.73826993, 0.48588124],
       [0.90816457, 0.02760697]])

In [93]:
a13

array([[0.30946072, 0.86109714],
       [0.41775177, 0.07454422],
       [0.17793225, 0.3608587 ],
       [0.73826993, 0.48588124],
       [0.90816457, 0.02760697]])

In [94]:
a12

array([0.30946072, 0.86109714, 0.41775177, 0.07454422, 0.17793225,
       0.3608587 , 0.73826993, 0.48588124, 0.90816457, 0.02760697])

In [95]:
np.sort(a12)[::-1] #descending order

array([0.90816457, 0.86109714, 0.73826993, 0.48588124, 0.41775177,
       0.3608587 , 0.30946072, 0.17793225, 0.07454422, 0.02760697])

In [96]:
np.random.rand(3,4) #3rd ways

array([[0.31317092, 0.32564617, 0.45616423, 0.77773549],
       [0.44327354, 0.20877904, 0.58724814, 0.65419246],
       [0.36040015, 0.98560952, 0.39085696, 0.80351155]])

In [97]:
np.random.rand(12)

array([0.0293951 , 0.19368957, 0.95751063, 0.18188733, 0.81359506,
       0.25304486, 0.48205539, 0.04329466, 0.98752301, 0.69451882,
       0.39300866, 0.86531795])

In [98]:
np.random.rand(2,3,4)

array([[[0.46123713, 0.42931073, 0.33844088, 0.41536563],
        [0.85656988, 0.60159505, 0.24762374, 0.0269041 ],
        [0.28217203, 0.8827588 , 0.43513845, 0.36710847]],

       [[0.56842162, 0.12806044, 0.38441728, 0.62266053],
        [0.49892143, 0.86416305, 0.92946126, 0.17644487],
        [0.98230349, 0.96296876, 0.17096612, 0.39859632]]])

In [ ]:
#randn()--generates array with elements of -3 to +3 range 

In [101]:
a13=np.random.randn(20)#1d array
a13

array([ 2.04637265, -0.20819426,  2.13591745, -0.22513384, -2.43655139,
       -1.21999566,  0.16712293,  1.72386394, -0.20614685, -0.40953892,
       -0.70429999, -1.60016665, -0.8118234 , -1.10124113,  0.00726256,
        0.87659715, -1.25136241,  0.21478301, -0.24628487, -1.79878845])

In [ ]:
#randint() --generates integer random numbers within a given  range 

In [102]:
np.random.randint(2,19) #generates single random int within 2 & 19

12

In [104]:
a15=np.random.randint(1,100,8)#betweem 1 to 100 ,8 elements will be generated
a15

array([40, 33, 10,  9, 98, 85, 78, 35])